<a href="https://colab.research.google.com/github/msiplab/AtipWork/blob/develop/python/sample01_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 基本操作 
# 
# 画像処理特論
# 
# 村松 正吾 
# 
# 動作確認: Python 3.7, PyTorch 1.8

In [2]:
# Basic operations
# 
# Advanced Topics in Image Processing
# 
# Shogo MURAMATSU
# 
# Verified: Python 3.7, PyTorch 1.8
import torch


In [3]:
# (Definition of matrix $\mathbf{A}$)
# 
# $$\mathbf{A}=\left(\begin{array}{ll}1 & 2 \\ 3 & 4 \\ 5 & 6\end{array}\right)$$

A = torch.tensor([ \
    [ 1, 2 ],
    [ 3, 4 ],
    [ 5, 6 ] ])
A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [4]:
# (Definition of matrix $\mathbf{B}$ )
# 
# $$\mathbf{B}=\left(\begin{array}{lll}1 & 2 & 3 \\ 4 & 5 & 6\end{array}\right)$$

B = torch.tensor([ \
    [ 1, 2, 3 ],
    [ 4, 5, 6 ] ])
B

tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
# (Matrix product)
# 
# $$\mathbf{C}=\mathbf{A B}$$

C = A @ B
C

tensor([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])

In [6]:
# © Copyright, Shogo MURAMATSU, All rights reserved.